# ===== Environment =====
executor: slurm
use-conda: True
use-apptainer: True
apptainer-args: "--bind /scratch/alpine --bind /pl/active/Anschutz_BDC"
slurm-qos: "cpu-normal"
slurm-logdir: "results/logs"
slurm-keep-successful-logs: True

# ===== Default resources =====

default-resources:
    slurm_partition: "acpu"
    slurm_account:   "amc-general"
    runtime: 60
    mem: "4GB"

# ===== Rule-specific resources =====
set-resources:
    fastq_screen:
        runtime: 720
        mem: "4GB"
    fastqc:
        runtime: 60
        mem: "4GB"
    fastqc_trim:
        runtime: 60
        mem: "4GB"
    fastqc_summary:
        runtime: 10
        mem: "4GB"
    bbduk:
        runtime: 180
        mem: "4GB"
    cutadapt:
        runtime: 180
        mem: "4GB"
    no_trim:
        runtime: 5
        mem: "1GB"
    align:
        runtime: 1200
        mem: "15GB"
        tasks: 1
        cpus_per_task: 6
        nodes: 1
    aligment_stats:
        runtime: 30
        mem: "1GB"
    remove_mito:
        runtime: 120
        mem: "3GB"
    mark_duplicates:
        runtime: 360
        mem: "60GB"
    remove_duplicate_reads:
        runtime: 120
        mem: "3GB"
    dup_stats:
        runtime: 10
        mem: "1GB"
    macs3:
        runtime: 180
        mem: "30GB"
    macs2:
        runtime: 180
        mem: "30GB"
    overlapping_peaks:
        runtime: 180
        mem: "30GB"
    make_bigwig:
        runtime: 180
        mem: "40GB"
    make_sample_sheet: 
        runtime: 30
        mem: "5GB"
    merge_fastq:
        runtime: 30
        mem: "3GB"
