##### aligning information #####

# The path to the scratch direcotry.
SCRATCH_DIR:
  "/scratch/alpine/chill1@xsede.org"

# The path to your working directory. Leaving this blank will just make it so this full path
# is in your scratch space
BASE_PATH:
  "/pl/active/Anschutz_BDC"

# Sample sheet. This is the path to the sample sheet. Should be a tab delimited
# tsv file with the one column titled "sample" and a second column titled
# "fastq1" with filenames relating to each sample. If paired end sequencing was
# done, another columen should be titled "fastq2" with filenames for read 2.
SAMPLE_TABLE:
  "files/samples.tsv"

# Project the name of the project
PROJECT:
  "dylan_atac"

# Reference. This should be the path to a directory created using bowtie2
GENOME:
  /pl/active/Anschutz_BDC/resources/ref/indices/bowtie2/mouse/GRCm38/GRCm38

# GTF. This is a path to the gtf file. Should match the genome fa used
GTF:
  /pl/active/Anschutz_BDC/resources/ref/annotation/mouse/GRCm38/gtf/Mus_musculus.GRCm38.96.gtf

# Path to results directory
RESULTS:
  "results"

# Path to adaptors file. This is included in the bbtools package under .../bbmap/resources/adaptors.fa
# Not necessary if not using bbduk for trimming
ADAPTORS:

GENOME_SIZE:
  1.87e9

# Trim method, can be "bbduk", "cutadapt", or "no"
TRIM_METHOD:
  "cutadapt"

# The qvalue cutoff for macs2, if not included, the default of 0.05 will be used
QVALUE:
  0.01

# Parameters for paired end or single end experiments
PE:
    cutadapt:      " -m 20 -a 'CTGTCTCTTATACACATCTCCGAGCCCACGAGAC' -A 'CTGTCTCTTATACACATCTGACGCTGCCGACGA' "
    featureCounts: " --extraAttributes 'gene_name,gene_biotype' -s 1 -p -B "
    bbduk:         "ktrim=r k=23 mink=11 hdist=1 tpe tbo"


SE:
    cutadapt:      " -m 20 -a 'CTGTCTCTTATACACATCTCCGAGCCCACGAGAC' "
    featureCounts: " --extraAttributes 'gene_name,gene_biotype' -s 1 "
    bbduk:         "ktrim=r k=23 mink=11 hdist=1 tpe tbo"

BLACKLIST:
  "genome/mm10.blacklist.bed"

# Path to a file containing chromosome sizes to be used by HMMRATAC
CHR_SIZE:
  "files/GRCm38_chrsizes.txt"

# Path to the HMMRATAC jar file
HMMRATAC_FILE:
  "bin/HMMRATAC_V1.2.10_exe.jar"

# Containers
GENERAL_CONTAINER:
  "docker/general_docker/atac_chip_v1.sif"

# The container for running picard tools
PICARD_CONTAINER:
  "docker/picard_docker/picard_3.4.0.sif"

R_CONTAINER:
  "docker/r_docker/atac_chip_r_v1_dockerhub.sif"

# Path to fastq_screen container
FASTQ_SCREEN:
  "docker/fastq_screen/fastq_screen_v1.2.sif"

# Path to where fastq screen references will be saved. If the references have already been
# downloaded they won't be downloaded again
# Alternatively, you can pass the path to a fastq screen config file
FASTQ_SCREEN_DATA:
  "/pl/active/Anschutz_BDC/resources/ref/indices/fastq_screen/FastQ_Screen_Genomes/fastq_screen.conf"
  #"/pl/active/Anschutz_BDC/resources/ref/indices/fastq_screen"

# ATAC qc files
# Provide the path to seq info and transcripts for your species
SEQ_INFO:
  "genome/mm10_seq_info.rds"

TRANSCRIPTS:
  "genome/mm10_transcripts.rds"

BSGENOME:
  "genome/mm10_genome.rds"
