[workspace]
name = "atacseq"
version = "0.1.0"
description = "Bioinformatics environment"
channels = ["conda-forge", "bioconda", "agbiome"]
platforms = ["linux-64"]

[dependencies]
pip = "==25.0"
pysam = "==0.23.0"
bowtie2 = "==2.5.4"
macs3 = "==3.0.3"
cutadapt = "==5.0"
bbtools = "==37.62"
fastqc = "==0.12.1"
samtools = "==1.21"
subread = "==2.1.1"
bedtools = "==2.31.1"